// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpcbjmfvonxaiolxqmyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY2JqbWZ2b254YWlvbHhxbXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTE2NDUsImV4cCI6MjA1OTc2NzY0NX0.pRk2t33UgM36kVyfApwJActJ7nZC6z8JbHjhxJ9inEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);